//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapVisualizer
{
    using System;
    using System.Collections.Generic;
    
    internal partial class city
    {
        public string city_name { get; set; }
        public Nullable<int> city_nr { get; set; }
        public string is_water { get; set; }
        public string show_color { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometrie_fld { get; set; }
        public long id { get; set; }
    }
}
